Repository Team13-MoaMoa/frontend, pull requests merged in 2023-11, with the labels that each got.

#46 Feat/#45 쪽지 페이지 API 연동
  package.json
  src/assets/emptyNote.json
  src/components/NoteDetail/index.tsx
  src/components/NoteUserList/index.tsx
  src/components/SendNote/index.tsx
  src/pages/note/index.tsx
  src/types/note/index.ts
  yarn.lock
Labels: FEAT

#49 Feat/#47 게시글 상세 페이지 상세 구현
  next.config.js
  src/api/note.ts
  src/api/post.ts
  src/components/Comment/index.tsx
  src/components/SendNote/index.tsx
  src/hook/useInput.ts
  src/pages/note/index.tsx
  src/pages/posts/[postId].tsx
  src/pages/write/index.tsx
Labels: FEAT

#48 Feat/#43 마이페이지 찜 하기 , 내가 쓴 글 api 연동
  src/api/axiosCustom.ts
  src/assets/bear.png
  src/components/Nav/index.tsx
  src/components/Profile/index.tsx
  src/components/SelectBar/index.tsx
  src/components/UserProjects/index.tsx
  src/pages/mypage/index.tsx
  src/pages/posts/[postId].tsx
  src/types/mypage/index.ts
Labels: FEAT

#51 fix: 로그인 유지 방식 변경
  src/components/Nav/index.tsx
Labels: FIX

#53 Design/#52 게시글 상세 페이지 UI 수정
  src/pages/posts/[postId].tsx
Labels: FIX, DESIGN

#57 feat : 쪽지 목록 revalidate 구현
  src/api/note.ts
  src/components/NoteDetail/index.tsx
  src/components/NoteUserList/index.tsx
  src/pages/note/index.tsx
  src/pages/posts/[postId].tsx
Labels: FEAT, REFACTOR

#56 refactor: footer바 , 텍스트 박스 크기 수정
  src/pages/mypage/index.tsx
Labels: REFACTOR

#58 fix : 쪽지 refetch 수정
  src/api/note.ts
  src/components/NoteDetail/index.tsx
  src/components/SendNote/index.tsx
  src/pages/note/index.tsx
  src/pages/posts/[postId].tsx
Labels: FIX, FEAT

#64 Refactor/#62 로그인 유저 리덕스 수정
  src/api/userAuth.ts
  src/components/Comment/index.tsx
  src/components/CompleteProfile/index.tsx
  src/components/EditProfile/index.tsx
  src/components/Nav/index.tsx
  src/components/Profile/index.tsx
  src/components/ProfileZone/index.tsx
  src/components/_layout.tsx
  src/pages/callback/github/index.tsx
  src/pages/callback/kakao/index.tsx
  src/pages/login/step3.tsx
  src/pages/posts/[postId].tsx
Labels: FIX, FEAT, REFACTOR, DESIGN

#66 fix : 로그인 프로필 사진 업데이트 버그 수정
  src/pages/callback/github/index.tsx
  src/pages/callback/kakao/index.tsx
Labels: FIX
